### ISSUE TITLE
Support printing package name for mono repos

### ISSUE THREAD

**Issue by geraldus** [ocharles/weeder#103]
Hi!  I have a mono repo with several packages inside.  When running `weeder` in project root it prints locations without a package info.  Consider we have
```
packages
  - pacakageA
    - src
      - Common.hs
      - … 
  - pacakageB
    - src
      - Common.hs
      - …
project.cabal
…
```
If both Common modules have unused functions weeder will output something like
```
src/Common.hs:111: unusedFuncInPackageA
src/Common.hs:123: unusedFuncInPackageB
```

Is it possible to make weeder to provide a package name?  Or maybe a flag to enable printing absolute file paths?  The latter may be very useful in VSCode for example since it supports jumping to location by Ctrl+clicking on paths in integrated terminal.

It looks like a trivial change and I would be glad to make a PR if someone provide a guidance or details how to implement this.

Thanks.

**Comment by NorfairKing** [comment]
@geraldus did you ever make a PR?

**Comment by geraldus** [comment]
> @geraldus did you ever try implementing this?

Hi! Unfortunately not. Although it seems trivial, I have no chance to try it.

**Comment by geraldus** [comment]
@ocharles Cool! Thanks!
