### ISSUE TITLE
Support sorting output by descending line number

### ISSUE THREAD

**Issue by geraldus** [ocharles/weeder#104]
Hi!  I've found very useful to sort weeder's output by line number in a descending order.  If I clean up my code base from top to bottom line numbers in weeder output becomes inaccurate because code shifts up when deleting lines.  This is not a case if I do clean up from bottom to up. Manual lines sorting is quite tedious work eating time when dealing with project with a lot of dead code to be cleaned.

Thanks.

**Comment by ocharles** [comment]
Are you looking for more than just `weeder | tac`?

**Comment by geraldus** [comment]
Thank you for pointing this out! Unfortunatelly, I can't check it at the moment. Closing this for now.
