### ISSUE TITLE
Error constructing build plan on stackage lts-15.3

### ISSUE THREAD

**Issue by eahlberg** [ocharles/weeder#11]
I get the following error when trying to use Weeder 2.0.1 with stackage [lts-15.3](https://www.stackage.org/lts-15.3):
```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for weeder-2.0.1:
    generic-lens-1.2.0.1 from stack configuration does not match ^>=1.1.0.0 || ^>=2.0.0.0  (latest matching version is 2.0.0.0) needed since weeder is a build target.

Some different approaches to resolving
this:

  * Set 'allow-newer: true'
    in /root/.stack/config.yaml to ignore all version constraints and build anyway.

  * Recommended action: try adding the
    following to your extra-deps
    in /root/project/stack.yaml:

- generic-lens-2.0.0.0@sha256:7409fa0ce540d0bd41acf596edd1c5d0c0ab1cd1294d514cf19c5c24e8ef2550,3866

Plan construction failed.

Exited with code exit status 1
```

From my understanding this is because [generic-lens 1.2.0.1](https://www.stackage.org/lts-15.3/package/generic-lens-1.2.0.1) is on lts-15.3, which represents a major version change according to [Haskell PVP](https://pvp.haskell.org/), thus the configuration does not match.

If you're open to PR's I'd be glad to help but I'm not sure what would be the appropriate solution for this. Would it work to use `generic-lens ^>= 1.1.0.0 || ^>= 1.2.0.0 || ^>= 2.0.0.0` instead of `generic-lens ^>= 1.1.0.0 || ^>= 2.0.0.0`?

**Comment by ocharles** [comment]
Yea, it sounds like I just need to add ^>= 1.2.0.0. I'll give that a try!

**Comment by ocharles** [comment]
It doesn't seem to build with generic-lens-1.2.0.1 here - https://github.com/ocharles/weeder/runs/512277754?check_suite_focus=true#step:4:10734. Can you check if it works for you?

**Comment by eahlberg** [comment]
Cool, thanks!
