### ISSUE TITLE
No tag for release 2.2.0

### ISSUE THREAD

**Issue by chessai** [ocharles/weeder#119]
Wanted to use weeder for a project on 8.10.7, and saw that there was no tag or release for 2.2.0. Afaict this is the only release like this

**Comment by ocharles** [comment]
Thanks, good spot. https://github.com/ocharles/weeder/commit/b810f199226f624e467f506ea4f5ec5223f66b71 is the commit, I'll push a tag when I'm next at my desktop

**Comment by ocharles** [comment]
Fixed!
