### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tfausak** [ocharles/weeder#125]
There are lots of great changes on the `master` branch. Can we get a new release to Hackage so they're easier to use? Thanks!

**Comment by ocharles** [comment]
I think it probably is time for a release! I'll see what I can do tomorrow

**Comment by ocharles** [comment]
Sorry, I haven't been able to get to this yet, but it is on my to-do list.

**Comment by ocharles** [comment]
[2.6.0 released!](https://hackage.haskell.org/package/weeder-2.6.0)

**Comment by tfausak** [comment]
Thanks!
