### ISSUE TITLE
Keep the order of instance in deriving clauses

### ISSUE THREAD

**Issue by NorfairKing** [ocharles/weeder#150]
(Yes I'm still weeding my projects. I've already removed more than 2K LOC, thank you!!)
This is a minor thing but I often see things like this:

```
src/Centjes/Report/Balance.hs:54: (Instance) :: Eq ann => Eq (BalancedLedger ann)
src/Centjes/Report/Balance.hs:54: (Instance) :: Generic (BalancedLedger ann)
src/Centjes/Report/Balance.hs:54: (Instance) :: Show ann => Show (BalancedLedger ann)
```

and then I look at the file and see

```
deriving (Show, Eq, Generic)
```

It would be much easier to weed if these were in the same order.

**Comment by ocharles** [comment]
Right, I think we only sort by line number. I don't think it would be hard to then sort by column
