### ISSUE TITLE
Wrong weed attribution

### ISSUE THREAD

**Issue by ShrykeWindgrace** [ocharles/weeder#153]
Hi!

I faced a wrong attribution of weeds  in the `2.8.0` version.

Essentially, it seems that if hie folder has subfolder with identical file names (e.g. Main.hie), then the weeds in subsequent `Main.hie` files are reported as if they were in the first one.

You can find an example here: https://github.com/ShrykeWindgrace/weederwrong-attribution

I do not know whether that's an issue with my configuration or a weeder issue.

Cheers!

**Comment by ocharles** [comment]
Can you try upgrading your version of Cabal to the very latest? I think that might solve this problem.

**Comment by ShrykeWindgrace** [comment]
> Can you try upgrading your version of Cabal to the very latest? I think that might solve this problem.

Thanks for your prompt answer!

I have the following:
```console
$ cabal --version
cabal-install version 3.10.3.0
compiled using version 3.10.3.0 of the Cabal library
```
`cabal` is installed via `ghcup`. I updated `cabal-version`  to `3.8` in my `*.cabal` file, but I still observe the same behavior.

Is there anything else cabal-related to upgrade?
