### ISSUE TITLE
wildcard roots

### ISSUE THREAD

**Issue by elaforge** [ocharles/weeder#17]
Weeder on my project emits around 3000 weeds, almost all of which seem to be false positives.  It looks like the main reason is that I use the GHC API to call functions at runtime.  I could add them all as roots, but there's around 700 of them.  But a prefix match in the roots list would solve it nicely.  E.g. I could write "Cmd.Repl.L*" and have it match Cmd.Repl.LAlloc.kebyar and Cmd.Repl.LBlock.append.

A suffix match could be useful too, e.g. I have about 30 separate binaries, and while I could copy all the 'main's in, if I had many more I'd start wanting to generate the config file to avoid that.  A simpler solution would be to assume anything named 'main' is a root with "*.main".

There are also a number of false positives that are definitely called from a root.  I suspect it's because there are multiple build modes (debug, opt, test, profile), and weeder doesn't merge multiple hie files for a single module, so the last one wins.

**Comment by ocharles** [comment]
Everything in the Dhall configuration is a regular expression, so I think you can already do everything you want! Is that what you're looking for?

**Comment by ocharles** [comment]
> There are also a number of false positives that are definitely called from a root. I suspect it's because there are multiple build modes (debug, opt, test, profile), and weeder doesn't merge multiple hie files for a single module, so the last one wins.

As long as these are separate `.hie` files, it will merge them. Weeder generates a graph for each file, and then overlays them all. This sounds like something worth investigating though, could you open a separate issue?

**Comment by elaforge** [comment]
Oh, I missed that those were regexes!  I assumed you wouldn't want to do that since module names naturally have lots of dots in them and it's easy to forget to double-backslash them all (weeder itself doesn't suggest the backslashes), but I guess the chance of having modules named `A.B` and `AsB` is low-ish.  It could be confusing if it happened though.

Putting in the regex took out about 1000 of the non-weeds.  A few hundred more were because I forgot to actually build all the binaries.  It looks like the remaining ~2000 are mostly legit weeds!  I underestimated how much junk accumulates.  I'll sort through them and make an issue if I find positives I can't explain.

BTW, in case you're interested, it takes me about 20-40s to run on about 168k lines of haskell.  That's not exactly speedy, but it's quick enough for me, and much much faster than `unused`, which is the other tool I know of that does this.  I don't know why `unused` is so slow.
