### ISSUE TITLE
Is it appropriate to warn about definitions in auto generated files

### ISSUE THREAD

**Issue by expipiplus1** [ocharles/weeder#22]
I'm not using `Paths_myPackageName` but it's generated anyway. Weeder warns me that all the definitions in that file are weeds.

**Comment by ocharles** [comment]
I don't think there's much I can do other than hard code a rule to ignore `Paths_`. For now, I've been adding a rule to ignore `^Paths_.*` in my `weeder.dhall`.

**Comment by expipiplus1** [comment]
Yeah, it's probably best there.
