### ISSUE TITLE
How to use the 2nd version with a library?

### ISSUE THREAD

**Issue by qrilka** [ocharles/weeder#25]
https://github.com/ocharles/weeder#calling-weeder talks about using `main` as a root for an executable but what should one do when using `weeder` on a library project? Do I need to list every export or maybe there is some other way around?

**Comment by ocharles** [comment]
At the moment the options are to either explicit write them down, or alternatively refer to them all via a test suite

**Comment by qrilka** [comment]
Thanks, does it mean that this could change is some not very distant future?
Maybe advice to use a test suite as an entry point could be helpful for newcomers while we have the current situation?

**Comment by ocharles** [comment]
> Thanks, does it mean that this could change is some not very distant future?

At one point in the past I had an option to root all exported functions, which we could bring back.

> Maybe advice to use a test suite as an entry point could be helpful for newcomers while we have the current situation?

Yes, this documentation would be useful. Would you be willing to change the `README.md`?
