### ISSUE TITLE
Ignore record field accessor functions option

### ISSUE THREAD

**Issue by AlistairB** [ocharles/weeder#28]
A lot of my weeds are along the lines of I have some record type eg.

```haskell
newtype Version
  = Version
      { _vVersion :: Text
      }
```

And weeder will complain that I never use `_vVersion`. This is because sometimes I might find it more readable to do something like `Version <$> someMonad` (or because I use the lens `vVersion` that I generate). Nonetheless, I like a consistent record type format and having these labeled field accessors available if I need them.

Would it be reasonable to have an option to ignore these weeds?

**Comment by ocharles** [comment]
If you name your fields with underscores, you could add a rule to not report anything that matches `\._`. Would that work?

**Comment by AlistairB** [comment]
Ah good point. That should work. Although, I now realise my problem is the opposite. It is complaining I am creating lenses that are unused. Ideally I would like to ignore these as well. I think I could generate them to be more matchable with regex to handle this. Regardless, weeder does handle these cases anyway. Thanks!

**Comment by AlistairB** [comment]
If anyone else faces a similar issue, I resolved it by prefixing all lenses with `l_` via

```haskell
import Control.Lens (DefName (..), FieldNamer, LensRules, defaultFieldRules, lensField, makeLensesWith)
import Language.Haskell.TH.Syntax (Dec, Name, Q, mkName, nameBase)

prefixWithL :: FieldNamer
prefixWithL _ _ fieldName =
  let fieldNameString = nameBase fieldName
      lAppendedName = mkName $ 'l' : appendLeadingUnderscoreIfMissing fieldNameString
   in [TopName lAppendedName]

appendLeadingUnderscoreIfMissing :: String -> String
appendLeadingUnderscoreIfMissing a@('_' : _) = a
appendLeadingUnderscoreIfMissing xs = '_' : xs

prefixWithLRules :: LensRules
prefixWithLRules = defaultFieldRules & lensField .~ prefixWithL

makeLensesPrefixL :: Name -> Q [Dec]
makeLensesPrefixL = makeLensesWith prefixWithLRules
```

then adding a root of `.+l_.+`
