### ISSUE TITLE
Weed package dependencies

### ISSUE THREAD

**Issue by AlistairB** [ocharles/weeder#29]
A feature of weeder 1.0 is:

> Your package depends on another package but doesn't use anything from it - the dependency should usually be deleted. This functionality is quite like packunused, but implemented quite differently.

It seems that weeder 2.0 does not have this feature. Is this feature planned to be added?

**Comment by ocharles** [comment]
I would love to have it, but AFAIK this information is not in HIE files. I believe it's also part of GHC now. I'll do a bit more research and try and provider more info. Right now weeder 2 cannot do thia

**Comment by AlistairB** [comment]
Actually, looks like ghc 8.10 has this feature now https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wunused-packages . Perhaps this should be out of scope for weeder?

**Comment by ocharles** [comment]
Sorry for not replying, but this would be put of scope for weeder for now, as .hie files dont contain this kind of information. They could, of course, but we'd need to change GHC first. I think using the GHC warning is the way to go

**Comment by AlistairB** [comment]
No problem! I just figured I would close this as `-Wunused-packages` had issues on GHC 8.10, but upon migrating to 9.0.2 it works perfectly.
