### ISSUE TITLE
Fix --root syntax in readme OR --help

### ISSUE THREAD

**Issue by pepeiborra** [ocharles/weeder#3]
One of these is wrong - the readme claims the syntax is `--root 'main Main main'` whereas the flag says `--root unit$Module.symbol`

**Comment by ocharles** [comment]
Thanks. I think the `--help` output is wrong - I find the spaces version easier to type. Do you have a preference?

**Comment by ocharles** [comment]
Ok, I've changed the whole UX here so I'll close this.
