### ISSUE TITLE
What does "Module not compiled" mean?

### ISSUE THREAD

**Issue by dnikolovv** [ocharles/weeder#31]
When I run weeder I simply get tons of `Module not compiled` modules and a huge list of redundant `build-depends` entries.

The problem is that some of these "redundant" build-depends entries are in fact used in the modules that aren't compiled.

How do I interpret this? Is there a way to force compilation of all modules?

**Comment by ocharles** [comment]
I have no idea what this means! If you are able, could you share an offending hie file? Please be aware that a single hie file contains the source code for the module that produced it

**Comment by dnikolovv** [comment]
Hey, sure! I'll share a file that doesn't leak anything important.

This is how the `Module not compiled` output that I was talking about looks like:

```plaintext
== Section library ==
Module not compiled
* CQRS.Projection.Class
* CQRS.Queryable.Class
Redundant build-depends entry
* data-has
```
I have trimmed it down a lot, there are a lot more modules (nearly all of them) that appear under `Module not compiled`.

Notice that `CQRS.Projection.Class` is there alongside with `data-has`. I'm attaching the module's hie file, where it's clearly visible that `data-has` is in fact being used. (it's a zip so GitHub doesn't complain about the format)

[Class.hie.zip](https://github.com/ocharles/weeder/files/4532926/Class.hie.zip)

This is the weeder configuration that I'm using (taken from the readme):

```dhall
{ roots = [ "^Main.main$" ], type-class-roots = True }
```

**Comment by seagreen** [comment]
Adding `-ddump-to-file -ddump-hi` in addition to `-write-ide-info` fixed this for me (GHC 8.10.3).

**Comment by seagreen** [comment]
Ah, but I'm all the way back on `weeder-1.0.9`. Any chance you're on an older version as well?

**Comment by seagreen** [comment]
That was it, I upgraded weeder and it's fixed.

**Comment by ocharles** [comment]
@dnikolovv Is this still an issue?

**Comment by dnikolovv** [comment]
@ocharles No idea! Haven't used it in years :sweat_smile:
