### ISSUE TITLE
Codebase is formatted weirdly, am I expected to use some code-formatter?

### ISSUE THREAD

**Issue by phadej** [ocharles/weeder#35]

**Comment by ocharles** [comment]
You are not expected to use a formatter, just your best effort to try and match surrounding style. I do think my style is at least consistent though, if not standard

**Comment by ocharles** [comment]
I should also say I don't really care how the code looks. I appreciate an effort but won't reject PRs based on format

**Comment by phadej** [comment]
Thanks for clarification
