### ISSUE TITLE
Weeds reported twice

### ISSUE THREAD

**Issue by pepeiborra** [ocharles/weeder#4]
Both the signature and the function definition are being reported as independent weeds in the tool output.

**Comment by ocharles** [comment]
They are separate lines, so this is somewhat by design. What do you think a better UI would be? Should I try and merge spans together into one big span? Type signatures don't necessarily appear adjacent to definitions, but if they are I can probably collapse the spans.

**Comment by pepeiborra** [comment]
If the module compiles there is a matching definition for every type signature, so the signatures can be ignored for the purposes of weeder, right?

**Comment by ocharles** [comment]
Ah yea, that's a fair point! I'll change it to ignore type signatures.
