### ISSUE TITLE
Would it be possible to support recent versions of dhall and optparse-applicative?

### ISSUE THREAD

**Issue by peti** [ocharles/weeder#44]
Hi Oliver, 

I've tried building weeder with the latest versions of its dependencies, but unfortunately the build fails. Is there any chance that you could look at this issue?

![image](https://user-images.githubusercontent.com/28323/92462318-9c86f700-f1ca-11ea-8bd5-7385a00a90c5.png)

Best regards,
Peter

**Comment by ocharles** [comment]
Hi @peti! Yes, of course - I'll take a look :)

**Comment by peti** [comment]
Thank you. BTW, I may have misremembered what happened during my last year. I've made another attempt and it now it seems like bumping the version constraints is all there is to it -- the build works fine with the new versions.

**Comment by ocharles** [comment]
`weeder-2.1.1` has been released which should support both of these.

**Comment by peti** [comment]
It doesn't look like the 2.1.1 release would accept `optparse-applicative-0.16.0.0`. I'm getting the following build error during configure:

    optparse-applicative >=0.14.3.0 && <0.15 || >=0.15.1.0 && <0.16

**Comment by ocharles** [comment]
Argh, I forgot to update the executable itself. Ok, we'll try again in 2.1.2 - I'll post here when it's done.

**Comment by ocharles** [comment]
Alright - give 2.1.2 a try!
