### ISSUE TITLE
Removed modules appear as weeds until stack clean

### ISSUE THREAD

**Issue by pbrisbin** [ocharles/weeder#48]
I'm starting to bring weeder-2 in on some larger projects and it's working amazingly, thanks for it!

One issue is that when I identify an entire module to remove, it still appears as weeds afterwards. Presumably, this is because nothing has cleaned up the old `.hie` files, so weeder still looks at them. If I issue a `stack clean` it works.

This is particularly problematic on CI where we work very hard to cache the working files and avoid clean builds. Busting the entire CI cache when/if we remove Haskell modules is effective, but a pretty big (and non-obvious) hammer.

I'm just wondering if I'm missing a lever or better workaround for this situation.

**Comment by ocharles** [comment]
Related: https://github.com/ocharles/weeder/issues/6
