### ISSUE TITLE
Pattern synonyms lead to false positives

### ISSUE THREAD

**Issue by pepeiborra** [ocharles/weeder#5]
Weeder reports false positives for identifiers that are only used inside pattern synonyms

**Comment by ocharles** [comment]
Great spot! Could you provide a minimal example?

**Comment by expipiplus1** [comment]
Minimal repro: https://github.com/expipiplus1/weeder-pattern-synonyms

Note the false positive and false negative cases.

**Comment by aryairani** [comment]
Is there anything I can do to help get this fixed?  I don't think I can do it alone, though.

**Comment by amesgen** [comment]
I pushed a fix in #79. The false negative in @expipiplus1's example seems to have been fixed already, but the false positive is taken care of by #79.

**Comment by expipiplus1** [comment]
Thanks!

**Comment by aryairani** [comment]
Thanks @amesgen (I'm not a maintainer)
