### ISSUE TITLE
early cutoff or other means of internal visibility?

### ISSUE THREAD

**Issue by shapr** [ocharles/weeder#63]
I tried to use weeder with a minimal weeder.dhall ( `{ roots = [ "^Main.main$", "^Paths_.*"], type-class-roots = True }` ) on the [haskell-language-server repo](https://github.com/haskell/haskell-language-server/) and killed weeder three hours later after it exceeded 128 GB RAM usage (that's all the ram I have).

Is there some way to get more info out of weeder about what happened and how I could have helped it along?

**Comment by ocharles** [comment]
Ouch! I haven't seen that, but that sounds like a classic memory leak to me. I don't think there is any way to get more info from `weeder` itself - but we could look at using standard tools like `eventlog2html` to see what's going on.

**Comment by shapr** [comment]
For some reason I can't get weeder to report more than zero weeds on any project so this issue is :suspect: suspect, and possibly invalid.
