### ISSUE TITLE
weeder without stack?

### ISSUE THREAD

**Issue by LeventErkok** [ocharles/weeder#76]
I was able to use earlier versions of weeder, with the following incantation:

```
weeder --config ./scripts/weeder.dhall
```

This doesn't seem to be supported any longer:

```
$ weeder --config ./scripts/weeder.dhall
Unknown flag: --config
```

Even if I run it without a config file, I get:

```
$ weeder
weeder: stack: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

I gather this means weeder now requires `stack`? I'm running on a cabal-only system and installing/running `stack` isn't really an option.

**Comment by ocharles** [comment]
Are you sure you're trying to run weeder 2.0? It looks like your `weeder` here is an old version (before my rewrite). `weeder` now has nothing to do with `stack`

**Comment by LeventErkok** [comment]
@ocharles 

Indeed, I was running weeder 1.0.9.

I'm on GHC-9.0.1, and I didn't pay attention to what `cabal` did. It turns out with GHC 9.0.1, a simple `cabal new-install weeder` installs weeder 1.0.9; as I guess that version had compatible bounds with base 4.15.

I see that #75 and #65 are relevant in this context. I'll comment there.
