### ISSUE TITLE
Misleading error message on GHC version mismatch

### ISSUE THREAD

**Issue by robx** [ocharles/weeder#8]
Running weeder (built with GHC 8.8.3) against a project that was built with GHC 8.8.2, `.hie` files, I get the following error:

```
$ weeder
weeder: weeder: panic! (the 'impossible' happened)
  (GHC version 8.8.3 for x86_64-apple-darwin):
	readHieFile: hie file versions don't match for file: /s/puzzle-draw/.stack-work/dist/x86_64-osx/Cabal-3.0.1.0/build/Parse/Util.hie Expected 8083 but got 8082

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

I suspect there's no GHC bug here, so as an immediate improvement I'd suggest catching the exception and notifying the user that `weeder` the project has to be compiled with the same GHC version that `weeder` was built with.

(I'd also suggest documenting this requirement in the README, or could it be worked around? Could weeder be hooked more directly into the build process as a GHC plugin or similar?)

**Comment by recursion-ninja** [comment]
I just ran into this today when testing out the new GHC-8.10.1 compiler, using a version of `weeder` I built with GHC-8.8.3.
