### ISSUE TITLE
Weeder runs sequentially

### ISSUE THREAD

**Issue by eborden** [ocharles/weeder#80]
Weeder does not take advantage of concurrent Haskell.

At Freckle we run our builds on multi core machines. If a build is going slower than we need, increasing the size of the machine is a relatively cheap way to gain performance.

`weeder` is a fly in that ointment. It currently takes 4 minutes to complete on our primary repository and we cannot "throw money" at the problem by increasing concurrency.

Introducing concurrency into `weeder` would allow it to gain performance in a typical GHC build scenario (multi core machines).

**Comment by ocharles** [comment]
I don't really know how to parallelize weeder. I could read all hie files in parallel (which already assumes IO won't be a bottleneck), but I don't think that's the slow part. The slow part is the reachability check and I don't know how to do that concurrently. Without help, there's probably not much I can do here

**Comment by eborden** [comment]
@ocharles I am also not sure how to add concurrency, though a work stealing queue of processed `hie` files feeding the single threaded algorithm is an interesting idea that I may explore.

**Comment by eborden** [comment]
With a pretty naive `Chan` based implementation the results add credence to your assumption that sequential `IO` is not the problem.

## Original
```
real    2m23.942s
user    2m21.681s
sys     0m2.047s
```

## Chan
```
real    5m34.569s
user    25m45.629s
sys     7m5.199s
```

```
+  hieReadChan <- newChan
+
+  async (readHieFilesConcurrently nameCache hieFilePaths hieReadChan)
+

-      for_ hieFilePaths \hieFilePath -> do
-        hieFileResult <- liftIO ( readCompatibleHieFileOrExit nameCache hieFilePath )
-        analyseHieFile hieFileResult
+      let consumeFiles = do
+            file <- liftIO (readChan hieReadChan)
+            case file of
+              HieFileFound hieFile -> do
+                analyseHieFile hieFile
+                consumeFiles
+              HieError err -> liftIO do
+                putStrLn err
+                exitFailure
+              Done -> pure ()
+      consumeFiles

+readHieFilesConcurrently :: Foldable f => NameCache -> f FilePath -> Chan HieQueue -> IO ()
+readHieFilesConcurrently nameCache hieFilePaths hieReadChan =  do
+  forConcurrently_ hieFilePaths \hieFilePath -> do
+    result <- readCompatibleHieFile nameCache hieFilePath
+    case result of
+      Right hieFile -> writeChan hieReadChan (HieFileFound hieFile)
+      Left err -> writeChan hieReadChan (HieError err)
+  writeChan hieReadChan Done
+

-readCompatibleHieFileOrExit :: NameCache -> FilePath -> IO HieFile
-readCompatibleHieFileOrExit nameCache path = do
+readCompatibleHieFile :: NameCache -> FilePath -> IO (Either String HieFile)
+readCompatibleHieFile nameCache path = do
...
```
