### ISSUE TITLE
Should we really set "package *"?

### ISSUE THREAD

**Issue by tomjaguarpaw** [ocharles/weeder#91]
[The README recommends](https://github.com/ocharles/weeder/blob/5e4a9f5788d5dbff830ae77812f9cecf0dad4fde/README.md?plain=1#L28-L31) `package *` in the `cabal.project.local`. But that seems to rebuild not only all packages but also all dependencies. Is there something else that could be suggested there that means "all local packages but not all packages depended upon"?

**Comment by ocharles** [comment]
Hmm, I guess because I use Nix & Haskell.nix, this doesn't happen for me. I don't know what a better option is, but if you find one I'll happily take a PR!

**Comment by tomjaguarpaw** [comment]
For now I will just manually specify the particular package(s), e.g.

```haskell
package opaleye
  ghc-options: -fwrite-ide-info
```

If I find a way of specifying "local packages" then I will make a PR.

**Comment by SamirTalwar** [comment]
With Cabal 3.8 and https://github.com/haskell/cabal/pull/7973, you can now do this:

```
program-options
  ghc-options: -fwrite-ide-info
```
