### ISSUE TITLE
False positive (and possibly negative) with top level pattern matching

### ISSUE THREAD

**Issue by amesgen** [ocharles/weeder#92]
In the following situation, `xxx` is marked as unused, even though it is not:

`Dep.hs`:
```haskell
module Dep (a, b) where

xxx :: Int
xxx = 3

a, b :: Int
(a, b) = (xxx, 1)
```
`Main.hs`:
```haskell
module Main where

import Dep

main :: IO ()
main = print a
```

Minimal reproducible example:
```shell
 $ git clone --branch weeder-pattern-bug --single-branch https://github.com/amesgen/stuff
 $ cd stuff
 $ weeder --version
weeder version 2.3.0
hie version 9001
 $ cabal build
 $ weeder
app/Dep.hs:4: xxx
```

---

Also, `b` in `Dep.hs` is not marked as unused, but I am not sure if this is intentional.

**Comment by ocharles** [comment]
Interesting! I imagine this pattern binding is going to be very hard. I think the best `weeder` will be able to do is say that `a` depends on `(xxx, 1)` and `b` depends on `(xxx, 1)`. I think anything more granular is going to need us to understand what the code means, which is generally outside the scope of weeder. Thanks for the minimal reproducible example!

**Comment by amesgen** [comment]
> I think the best `weeder` will be able to do is say that `a` depends on `(xxx, 1)` and `b` depends on `(xxx, 1)`.

I will take a look at this.

> I think anything more granular is going to need us to understand what the code means, which is generally outside the scope of weeder.

I agree, I suspect that implementing this would get out of hands very quickly.
